version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
#      - app2
#      - app3

  app1:
    build: .
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
    depends_on:
      - mongodb

#  app2:
#    build: .
#    environment:
#      - SPRING_DATA_MONGODB_HOST=mongodb
#    depends_on:
#      - mongodb
#
#  app3:
#    build: .
#    environment:
#      - SPRING_DATA_MONGODB_HOST=mongodb
#    depends_on:
#      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 